import {
  IoBarChartOutline,
  IoCalendarClearOutline,
  IoCalendarOutline,
  IoCardOutline,
  IoChatbubbleEllipsesOutline,
  IoCheckmarkCircleOutline,
  IoChevronBackOutline,
  IoClipboardOutline,
  IoCreateOutline,
  IoDocumentTextOutline,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFolderOutline,
  IoGridOutline,
  IoHelpBuoyOutline,
  IoListCircleOutline,
  IoLockClosedOutline,
  IoLogInOutline,
  IoLogOutOutline,
  IoMailOutline,
  IoMenuOutline,
  IoMoonOutline,
  IoNotificationsOutline,
  IoPeopleOutline,
  IoPersonAddOutline,
  IoPersonCircleOutline,
  IoRibbonOutline,
  IoSchoolOutline,
  IoSearchOutline,
  IoSettingsOutline,
  IoSunnyOutline,
  IoTimeOutline,
  IoWalletOutline,
} from "react-icons/io5";

const ICON_MAP = {
  dashboard: IoGridOutline,
  students: IoPeopleOutline,
  scores: IoClipboardOutline,
  analytics: IoBarChartOutline,
  results: IoDocumentTextOutline,
  schools: IoSchoolOutline,
  pending: IoTimeOutline,
  confirmed: IoCheckmarkCircleOutline,
  finance: IoWalletOutline,
  chat: IoChatbubbleEllipsesOutline,
  settings: IoSettingsOutline,
  attendance: IoCalendarOutline,
  fees: IoCardOutline,
  docs: IoFolderOutline,
  bell: IoNotificationsOutline,
  search: IoSearchOutline,
  logout: IoLogOutOutline,
  menu: IoMenuOutline,
  profile: IoPersonCircleOutline,
  sun: IoSunnyOutline,
  moon: IoMoonOutline,
  teachers: IoRibbonOutline,
  grading: IoCreateOutline,
  events: IoCalendarClearOutline,
  enroll: IoPersonAddOutline,
  support: IoHelpBuoyOutline,
  selection: IoListCircleOutline,
  email: IoMailOutline,
  lock: IoLockClosedOutline,
  back: IoChevronBackOutline,
  signin: IoLogInOutline,
  eye: IoEyeOutline,
  eyeOff: IoEyeOffOutline,
};

export function Ico({ name, size = 18, color = "currentColor", ...rest }) {
  const IconComponent = ICON_MAP[name] || IoGridOutline;
  return <IconComponent size={size} color={color} {...rest} />;
}
