create extension if not exists pgcrypto;

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  date date not null,
  status text not null default 'Present' check (status in ('Present', 'Absent', 'Late')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, date)
);

create index if not exists attendance_index_number_idx on public.attendance (index_number);
create index if not exists attendance_date_idx on public.attendance (date desc);

drop trigger if exists set_attendance_updated_at on public.attendance;
create trigger set_attendance_updated_at
before update on public.attendance
for each row execute function public.set_row_updated_at();

alter table public.attendance enable row level security;
drop policy if exists attendance_public_access on public.attendance;
create policy attendance_public_access on public.attendance
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.fees (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  term text not null default 'First Term',
  amount numeric(10,2) not null default 0,
  paid numeric(10,2) not null default 0,
  status text not null default 'unpaid' check (status in ('paid', 'partial', 'unpaid')),
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fees_student_id_idx on public.fees (student_id);
create index if not exists fees_index_number_idx on public.fees (index_number);

drop trigger if exists set_fees_updated_at on public.fees;
create trigger set_fees_updated_at
before update on public.fees
for each row execute function public.set_row_updated_at();

alter table public.fees enable row level security;
drop policy if exists fees_public_access on public.fees;
create policy fees_public_access on public.fees
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  class text,
  phone text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists teachers_name_idx on public.teachers (name);

drop trigger if exists set_teachers_updated_at on public.teachers;
create trigger set_teachers_updated_at
before update on public.teachers
for each row execute function public.set_row_updated_at();

alter table public.teachers enable row level security;
drop policy if exists teachers_public_access on public.teachers;
create policy teachers_public_access on public.teachers
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date,
  type text not null default 'event' check (type in ('event', 'exam', 'meeting')),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_event_date_idx on public.events (event_date asc nulls last);

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.set_row_updated_at();

alter table public.events enable row level security;
drop policy if exists events_public_access on public.events;
create policy events_public_access on public.events
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.app_settings (
  id integer primary key default 1,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (id = 1)
);

drop trigger if exists set_app_settings_updated_at on public.app_settings;
create trigger set_app_settings_updated_at
before update on public.app_settings
for each row execute function public.set_row_updated_at();

alter table public.app_settings enable row level security;
drop policy if exists app_settings_public_access on public.app_settings;
create policy app_settings_public_access on public.app_settings
for all to anon, authenticated
using (true)
with check (true);

insert into public.app_settings (id, config)
values (
  1,
  jsonb_build_object(
    'systemName', 'Campus Ghana',
    'academicYear', '2023/2024',
    'maxChoices', 6,
    'allowChanges', true,
    'emailNotifs', true,
    'maintenanceMode', false
  )
)
on conflict (id) do nothing;

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_email text not null,
  peer_id integer not null,
  text text not null,
  mine boolean not null default false,
  is_read boolean not null default false,
  read_at timestamptz,
  time text,
  created_at timestamptz not null default now()
);

alter table public.chat_messages add column if not exists is_read boolean not null default false;
alter table public.chat_messages add column if not exists read_at timestamptz;
update public.chat_messages set is_read = true where mine = true and is_read = false;

create index if not exists chat_messages_user_peer_idx on public.chat_messages (user_email, peer_id, id);
create index if not exists chat_messages_unread_idx on public.chat_messages (user_email, peer_id, mine, is_read);

alter table public.chat_messages enable row level security;
drop policy if exists chat_messages_public_access on public.chat_messages;
create policy chat_messages_public_access on public.chat_messages
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  subject text not null,
  score numeric(5,2) not null default 0,
  exam_type text not null default 'test',
  term text,
  academic_year text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scores_student_id_idx on public.scores (student_id);
create index if not exists scores_index_number_idx on public.scores (index_number);
create index if not exists scores_subject_idx on public.scores (subject);

drop trigger if exists set_scores_updated_at on public.scores;
create trigger set_scores_updated_at
before update on public.scores
for each row execute function public.set_row_updated_at();

alter table public.scores enable row level security;
drop policy if exists scores_public_access on public.scores;
create policy scores_public_access on public.scores
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  average_score numeric(5,2),
  aggregate numeric(5,2),
  grade text,
  rank integer,
  term text,
  academic_year text,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists results_student_id_idx on public.results (student_id);
create index if not exists results_index_number_idx on public.results (index_number);
create index if not exists results_rank_idx on public.results (rank);

drop trigger if exists set_results_updated_at on public.results;
create trigger set_results_updated_at
before update on public.results
for each row execute function public.set_row_updated_at();

alter table public.results enable row level security;
drop policy if exists results_public_access on public.results;
create policy results_public_access on public.results
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.profiles (
  id uuid primary key,
  email text,
  full_name text,
  role text not null default 'student' check (role in ('admin', 'student')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists profiles_role_idx on public.profiles (role);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_row_updated_at();

alter table public.profiles enable row level security;
drop policy if exists profiles_public_access on public.profiles;
create policy profiles_public_access on public.profiles
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password text not null,
  role text not null default 'student' check (role in ('admin', 'student')),
  full_name text,
  created_at timestamptz not null default now(),
  is_logged_in boolean not null default false,
  last_active timestamptz
);

create index if not exists users_role_idx on public.users (role);

alter table public.users enable row level security;
drop policy if exists users_public_access on public.users;
create policy users_public_access on public.users
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users (id) on delete set null,
  index_number text unique,
  index text,
  parent_contact text,
  full_name text,
  class text,
  region text,
  aggregate numeric(5,2),
  status text default 'pending',
  enrolled boolean default true,
  gender text,
  date_of_birth date,
  personal_contact text,
  home_address text,
  home_town text,
  place_of_residence text,
  postal_town text,
  po_box text,
  photo_url text,
  is_logged_in boolean not null default false,
  last_active timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'user_id'
  ) then
    create index if not exists students_user_id_idx on public.students (user_id);
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'index_number'
  ) then
    create index if not exists students_index_number_idx on public.students (index_number);
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'index'
  ) then
    create index if not exists students_index_idx on public.students ("index");
  end if;
end
$$;

drop trigger if exists set_students_updated_at on public.students;
create trigger set_students_updated_at
before update on public.students
for each row execute function public.set_row_updated_at();

alter table public.students enable row level security;
drop policy if exists students_public_access on public.students;
create policy students_public_access on public.students
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  region text,
  category text,
  type text,
  active boolean not null default true,
  cutoff numeric(5,2),
  slots integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists schools_name_idx on public.schools (name);
create index if not exists schools_category_idx on public.schools (category);

drop trigger if exists set_schools_updated_at on public.schools;
create trigger set_schools_updated_at
before update on public.schools
for each row execute function public.set_row_updated_at();

alter table public.schools enable row level security;
drop policy if exists schools_public_access on public.schools;
create policy schools_public_access on public.schools
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.school_selections (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  user_email text,
  status text not null default 'pending',
  approved boolean not null default false,
  selections jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_at timestamptz,
  rejection_reason text,
  reviewed_by text
);

create index if not exists school_selections_student_id_idx on public.school_selections (student_id);
create index if not exists school_selections_index_number_idx on public.school_selections (index_number);
create index if not exists school_selections_status_idx on public.school_selections (status);

drop trigger if exists set_school_selections_updated_at on public.school_selections;
create trigger set_school_selections_updated_at
before update on public.school_selections
for each row execute function public.set_row_updated_at();

alter table public.school_selections enable row level security;
drop policy if exists school_selections_public_access on public.school_selections;
create policy school_selections_public_access on public.school_selections
for all to anon, authenticated
using (true)
with check (true);