create table if not exists public.registered_schools (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  region text,
  category text,
  type text,
  active boolean not null default true,
  cutoff numeric(5,2),
  slots integer,
  tenant_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists registered_schools_name_idx on public.registered_schools (name);
create index if not exists registered_schools_region_idx on public.registered_schools (region);

drop trigger if exists set_registered_schools_updated_at on public.registered_schools;
create trigger set_registered_schools_updated_at
before update on public.registered_schools
for each row execute function public.set_row_updated_at();

alter table public.registered_schools enable row level security;
drop policy if exists registered_schools_public_access on public.registered_schools;
create policy registered_schools_public_access on public.registered_schools
for all to anon, authenticated
using (true)
with check (true);

create table if not exists public.school_admins (
  id uuid primary key default gen_random_uuid(),
  registered_school_id bigint not null references public.registered_schools (id) on delete cascade,
  full_name text not null,
  email text not null unique,
  phone text,
  password text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists school_admins_registered_school_id_idx on public.school_admins (registered_school_id);
create index if not exists school_admins_email_idx on public.school_admins (email);

drop trigger if exists set_school_admins_updated_at on public.school_admins;
create trigger set_school_admins_updated_at
before update on public.school_admins
for each row execute function public.set_row_updated_at();

alter table public.school_admins enable row level security;
drop policy if exists school_admins_public_access on public.school_admins;
create policy school_admins_public_access on public.school_admins
for all to anon, authenticated
using (true)
with check (true);

alter table public.users add column if not exists registered_school_id bigint references public.registered_schools (id) on delete set null;
alter table public.users add column if not exists managed_school_name text;

alter table public.profiles add column if not exists registered_school_id bigint references public.registered_schools (id) on delete set null;
alter table public.profiles add column if not exists managed_school_name text;