-- USERS TABLE
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password text not null,
  role text not null default 'student' check (role in ('admin', 'student')),
  full_name text,
  created_at timestamptz not null default now(),
  is_logged_in boolean not null default false,
  last_active timestamptz
);

-- PROFILES TABLE
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  email text,
  full_name text,
  role text not null default 'student' check (role in ('admin', 'student')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists profiles_role_idx on public.profiles (role);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users (id) on delete set null,
  index_number text unique,
  index text,
  parent_contact text,
  full_name text,
  class text,
  region text,
  aggregate numeric(5,2),
  status text default 'pending',
  enrolled boolean default true,
  gender text,
  date_of_birth date,
  personal_contact text,
  home_address text,
  home_town text,
  place_of_residence text,
  postal_town text,
  po_box text,
  photo_url text,
  is_logged_in boolean not null default false,
  last_active timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TEACHERS TABLE
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  class text,
  phone text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists teachers_name_idx on public.teachers (name);
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students (id) on delete cascade,
  index_number text,
  subject text not null,
  score numeric(5,2) not null default 0,
  exam_type text not null default 'test',
  term text,
  academic_year text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scores_student_id_idx on public.scores (student_id);
create index if not exists scores_index_number_idx on public.scores (index_number);
create index if not exists scores_subject_idx on public.scores (subject);

alter table public.scores enable row level security;

-- RLS POLICIES
-- Remove open policy if present
drop policy if exists scores_public_access on public.scores;

-- Admins can manage all scores
create policy "Admins can manage all scores"
on public.scores
for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.email = auth.email()
      and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.email = auth.email()
      and profiles.role = 'admin'
  )
);

-- Teachers can manage their subjects
create policy "Teachers can manage their subjects"
on public.scores
for all
to authenticated
using (
  exists (
    select 1 from public.teachers
    where teachers.email = auth.email()
      and scores.subject = any(string_to_array(teachers.subject, ','))
  )
)
with check (
  exists (
    select 1 from public.teachers
    where teachers.email = auth.email()
      and scores.subject = any(string_to_array(teachers.subject, ','))
  )
);
